# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6eff6e4d84b3ae6c36fbeefccb3b2f557f428fec8f5f98c092cc1dbea2d2e7b337772aaea4e8447772334994f82e867e439dc6b721869a2cd61b55d390e84dc

test:
  secret_key_base: d09384028f6e251a72380dd34cbb53832c77ebcb44e5e741faa2aa378c569923aef5cf72a179f38043fe350ef24b7f4085a8af9bab928212bff254b058ab7c62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
